# tests/test_rng.gd — reference-vector test for the mulberry32 port.
# The 100 expected uint32 numerators below were generated from Node.js (JS is truth):
#   first 100 outputs of mulberry32(42), each as round(f * 2^32) — exact, since f has
#   at most 32 significant bits. Comparing the INTEGER numerator sidesteps GDScript's
#   decimal float-literal parsing (which can be off by 1 ULP on some literals).

extends RefCounted

const TK := preload("res://tests/tk.gd")
const RNG := preload("res://src/rng.gd")


static func run() -> void:
	_test_first_100_outputs_seed_42_match_js_reference_vector()
	_test_second_instance_same_seed_replays_sequence()
	_test_different_seeds_diverge()


# First 100 outputs of mulberry32(42) as uint32 numerators, generated by Node.js.
const EXPECTED_SEED_42 := [
	2581720956, 1925393290, 3661312704, 2876485805, 750819978,
	2261697747, 1173505300, 2683257857, 3717185310, 2028586305,
	1073414265, 3788413843, 3202918453, 1318561460, 847198783,
	2150616774, 2948976162, 2622596789, 16505353, 2021992966,
	3596336860, 219942124, 2544012168, 135454488, 1146567233,
	265349060, 797528213, 3365309999, 2277774085, 116495015,
	743051824, 3619317939, 2094826994, 3474727257, 1372077750,
	1932287441, 160800198, 220730114, 2390577849, 2562933742,
	1053017205, 2773236351, 899840697, 1304079350, 3172354640,
	3688135315, 2181827449, 876989793, 1220659696, 1258389499,
	320810992, 2834076233, 2923880300, 2976790794, 3985042028,
	377819793, 4053312021, 1851721450, 4047124279, 589692171,
	476497268, 68044760, 1548102433, 2068982459, 2628185060,
	3863572076, 333213895, 3090649941, 4015226335, 1195080971,
	3034761162, 771473704, 2234741724, 3529998222, 517941159,
	4276235376, 2417208516, 3934706147, 1863974445, 2484436821,
	1447241123, 2560827451, 1387093168, 3132809236, 1267911619,
	1931716244, 3621197601, 2985282326, 4269246832, 3823371857,
	1854959739, 2341672574, 1271007590, 433265304, 2992396110,
	1345637321, 3375597684, 3885981145, 402186523, 2041792228
]


static func _test_first_100_outputs_seed_42_match_js_reference_vector() -> void:
	TK.begin("rng: first 100 outputs for seed 42 match the JS reference vector")
	var rng = RNG.new(42)
	for i in range(100):
		var got: int = rng.next_uint()
		var want: int = EXPECTED_SEED_42[i]
		TK.check(got == want, "output %d: got %d want %d" % [i + 1, got, want])
	TK.end()


static func _test_second_instance_same_seed_replays_sequence() -> void:
	TK.begin("rng: two instances with the same seed replay identical sequences")
	var a = RNG.new(42)
	var b = RNG.new(42)
	for i in range(50):
		TK.check(a.next_uint() == b.next_uint(), "output %d differs between twin instances" % (i + 1))
	TK.end()


static func _test_different_seeds_diverge() -> void:
	TK.begin("rng: different seeds produce different sequences")
	var a = RNG.new(1)
	var b = RNG.new(2)
	var same := true
	for i in range(50):
		if a.next_uint() != b.next_uint():
			same = false
			break
	TK.check(not same, "seeds 1 and 2 produced identical outputs")
	TK.end()
